"""add topic slug column

Revision ID: 2f41dc3393f9
Revises: 50f3cb025763
Create Date: 2026-01-28 19:19:28.697605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f41dc3393f9'
down_revision: Union[str, Sequence[str], None] = '50f3cb025763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# migration file
import json
from pathlib import Path

def upgrade():
    """Schema change kept; data step now a no-op.

    When this ran in January 2026 it also filled the new column from
    topic_slugs.json, generated by the script now archived at
    pipeline/iteration-1/07_load/initial_load/topic_slugs.py. That file is
    not in the repo, so only the column is added here.
    """
    op.execute('ALTER TABLE topics ADD COLUMN topic_normalised VARCHAR(255)')

def downgrade():
    op.execute('ALTER TABLE topics DROP COLUMN topic_normalised')
